-- Migration: Add all missing columns to cars table
-- Run this in Supabase SQL Editor

-- Add lifecycle columns
ALTER TABLE cars 
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS expired_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS retention_expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS last_extended_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS extension_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE;

-- Add missing columns from schema
ALTER TABLE cars 
ADD COLUMN IF NOT EXISTS is_dealer BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS country_code VARCHAR(10) DEFAULT '+971',
ADD COLUMN IF NOT EXISTS vin_number VARCHAR(17),
ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8),
ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

-- Also add to other listing tables if they exist
ALTER TABLE bikes 
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS expired_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS retention_expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS last_extended_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS extension_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_dealer BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS country_code VARCHAR(10) DEFAULT '+971',
ADD COLUMN IF NOT EXISTS vin_number VARCHAR(17),
ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8),
ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

ALTER TABLE license_plates 
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS expired_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS retention_expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS last_extended_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS extension_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_dealer BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS country_code VARCHAR(10) DEFAULT '+971',
ADD COLUMN IF NOT EXISTS vin_number VARCHAR(17),
ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8),
ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

ALTER TABLE car_parts 
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS expired_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS retention_expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS last_extended_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS extension_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_dealer BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS country_code VARCHAR(10) DEFAULT '+971',
ADD COLUMN IF NOT EXISTS vin_number VARCHAR(17),
ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8),
ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);
