export const UAE_EMIRATES = [
  "Abu Dhabi",
  "Dubai",
  "Sharjah",
  "Ajman",
  "Umm Al Quwain",
  "Ras Al Khaimah",
  "Fujairah",
];

export const DUBAI_AREAS = [
  "Al Barari",
  "Al Barsha",
  "Al Furjan",
  "Al Garhoud",
  "Nad Al Hamar",
  "Al Jaddaf",
  "Al Karama",
  "Al Khawaneej",
  "Al Mamzar",
  "Al Mizhar",
  "Al Nahda",
  "Al Quoz",
  "Al Qusais",
  "Al Safa",
  "Al Satwa",
  "Al Sufouh",
  "Al Twar",
  "Al Wasl",
  "Al Warqa",
  "Arabian Ranches",
  "Arabian Ranches 2",
  "Arabian Ranches 3",
  "Bluewaters Island",
  "Business Bay",
  "City Walk",
  "DAMAC Hills",
  "DAMAC Hills 2",
  "DIFC",
  "Discovery Gardens",
  "Downtown Dubai",
  "Dubai Creek Harbour",
  "Dubai Festival City",
  "Dubai Harbour",
  "Dubai Hills Estate",
  "Dubai Industrial City",
  "Dubai Investments Park (DIP)",
  "Dubai Marina",
  "Dubai Silicon Oasis",
  "Dubai Sports City",
  "Dubai Studio City",
  "Dubai South",
  "Dubai Production City",
  "Emaar South",
  "Emirates Hills",
  "Expo City Dubai",
  "International City",
  "Jebel Ali",
  "JLT (Jumeirah Lake Towers)",
  "Jumeirah",
  "Jumeirah Beach Residence (JBR)",
  "Jumeirah Bay Island",
  "Jumeirah Golf Estates",
  "Jumeirah Islands",
  "Jumeirah Park",
  "Jumeirah Village Circle (JVC)",
  "Jumeirah Village Triangle (JVT)",
  "Liwan",
  "Meydan",
  "Mohammed Bin Rashid City",
  "Mirdif",
  "Motor City",
  "Mudon",
  "Nad Al Sheba",
  "Nad Al Hamar",
  "Al Kifaf",
  "Palm Jumeirah",
  "Palm Jebel Ali",
  "Ras Al Khor",
  "Remraam",
  "Sheikh Zayed Road",
  "Sobha Hartland",
  "The Greens",
  "The Lakes",
  "The Meadows",
  "The Springs",
  "The Sustainable City",
  "The Villa",
  "Tilal Al Ghaf",
  "Town Square",
  "Umm Suqeim",
  "Wadi Al Safa",
  "Za'abeel 1",
  "Za'abeel 2",
  "Zabeel",
  "Zabeel 2",
  "Zabeel 3",
  "Zabeel District",
  "One Za'abeel",
  "Dubai Islands",
];

export const EMIRATE_AREAS = {
  Dubai: DUBAI_AREAS,

  "Abu Dhabi": [
    "Abu Dhabi Island",
    "Al Reem Island",
    "Al Raha Beach",
    "Al Raha Gardens",
    "Yas Island",
    "Saadiyat Island",
    "Al Maryah Island",
    "Hudayriyat Island",
    "Khalifa City",
    "Mohammed Bin Zayed City",
    "Shakhbout City",
    "Al Shamkha",
    "Al Reef",
    "Masdar City",
    "Mussafah",
    "Baniyas",
    "Al Wathba",
    "Zayed City",
    "Al Falah",
    "Corniche Area",
    "Al Khalidiyah",
    "Al Zahiyah",
  ],

  Sharjah: [
    "Al Nahda",
    "Al Majaz",
    "Al Qasimia",
    "Al Khan",
    "Muwaileh",
    "Al Taawun",
    "Aljada",
    "University City",
    "Muweilah Commercial",
    "Al Mamzar",
    "Rolla",
    "Al Nabba",
    "Tilal City",
    "Sharjah Sustainable City",
    "Al Suyoh",
    "Al Rahmaniya",
  ],

  Ajman: [
    "Al Nuaimiya",
    "Al Rashidiya",
    "Al Jurf",
    "Al Mowaihat",
    "Al Rawda",
    "Ajman Downtown",
    "Ajman Corniche",
    "Al Rumaila",
    "Al Zahya",
    "Al Helio",
    "Al Yasmeen",
    "Emirates City",
  ],

  "Umm Al Quwain": [
    "UAQ Marina",
    "Al Salamah",
    "Al Raas",
    "Falaj Al Mualla",
    "Al Dar Al Baida",
    "Al Abraq",
  ],

  "Ras Al Khaimah": [
    "Al Nakheel",
    "Al Hamra",
    "Al Hamra Village",
    "Al Marjan Island",
    "Khuzam",
    "Mina Al Arab",
    "Julphar",
    "Al Dhait",
    "Dafan Al Khor",
    "RAK City",
    "Al Jazirah Al Hamra",
  ],

  Fujairah: [
    "Fujairah City",
    "Al Faseel",
    "Sakamkam",
    "Dibba",
    "Mirbah",
    "Qidfa",
    "Masafi",
    "Al Badiyah",
  ],
};

export const getAreasForEmirate = (emirate) => EMIRATE_AREAS[emirate] || [];

export const WARRANTY_OPTIONS = [
  "No",
  "Yes",
  "Dealer Warranty",
  "Manufacturer Warranty",
  "Extended Warranty",
];

export const SERVICE_HISTORY_OPTIONS = [
  "No",
  "Yes",
  "Partial",
  "Agency Maintained",
  "Independent Garage",
];

export const DOOR_OPTIONS = ["2", "3", "4", "5"];

export const CYLINDER_OPTIONS = ["3", "4", "5", "6", "8", "10", "12", "16"];

export const MIN_CAR_YEAR = 1986;

export const getYearOptions = (minYear = MIN_CAR_YEAR) => {
  const maxYear = new Date().getFullYear() + 1;
  const years = [];
  for (let year = maxYear; year >= minYear; year -= 1) {
    years.push(String(year));
  }
  return years;
};

export const EXTERIOR_COLOR_OPTIONS = [
  "White",
  "Black",
  "Grey",
  "Silver",
  "Blue",
  "Red",
  "Green",
  "Yellow",
  "Orange",
  "Brown",
  "Beige",
  "Gold",
  "Purple",
  "Maroon",
  "Pink",
  "Other",
];

export const INTERIOR_COLOR_OPTIONS = [
  "Black",
  "Beige",
  "Brown",
  "White",
  "Grey",
  "Red",
  "Blue",
  "Tan",
  "Cream",
  "Orange",
  "Other",
];
export const FUEL_EFFICIENCY_OPTIONS = [
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30+",
];

export const TAG_OPTIONS = [
  // Note: these are allowed as selectable "extras" in the post form for now,
  // but the app deliberately does not display them on cards or listings.
  "Lady Driven",
  "Doctor Driven",
  "Expat Owned",
  "Executive Driven",
  "Mallu Owned",
  "British Owned",
];
