export const UAE_EMIRATES = [
  "Abu Dhabi",
  "Dubai",
  "Sharjah",
  "Ajman",
  "Umm Al Quwain",
  "Ras Al Khaimah",
  "Fujairah",
];

export const DUBAI_AREAS = [
  "Al Barari",
  "Al Barsha",
  "Al Furjan",
  "Al Garhoud",
  "Al Jaddaf",
  "Al Karama",
  "Al Khawaneej",
  "Al Mamzar",
  "Al Mizhar",
  "Al Nahda",
  "Al Quoz",
  "Al Qusais",
  "Al Safa",
  "Al Satwa",
  "Al Sufouh",
  "Al Twar",
  "Arabian Ranches",
  "Bluewaters Island",
  "Business Bay",
  "City Walk",
  "DAMAC Hills",
  "DIFC",
  "Discovery Gardens",
  "Downtown Dubai",
  "Dubai Creek Harbour",
  "Dubai Festival City",
  "Dubai Harbour",
  "Dubai Hills Estate",
  "Dubai Industrial City",
  "Dubai Investments Park (DIP)",
  "Dubai Marina",
  "Dubai Silicon Oasis",
  "Dubai Sports City",
  "Dubai Studio City",
  "Dubai South",
  "Emirates Hills",
  "International City",
  "Jebel Ali",
  "JLT (Jumeirah Lake Towers)",
  "Jumeirah",
  "Jumeirah Beach Residence (JBR)",
  "Jumeirah Golf Estates",
  "Jumeirah Islands",
  "Jumeirah Park",
  "Jumeirah Village Circle (JVC)",
  "Jumeirah Village Triangle (JVT)",
  "Liwan",
  "Meydan",
  "Mirdif",
  "Motor City",
  "Mudon",
  "Nad Al Sheba",
  "Palm Jumeirah",
  "Ras Al Khor",
  "Remraam",
  "Sheikh Zayed Road",
  "The Greens",
  "The Lakes",
  "The Springs",
  "The Sustainable City",
  "The Villa",
  "Town Square",
  "Umm Suqeim",
  "Wadi Al Safa",
];

export const EMIRATE_AREAS = {
  Dubai: DUBAI_AREAS,
  "Abu Dhabi": [
    "Abu Dhabi Island",
    "Al Reem Island",
    "Al Raha Beach",
    "Yas Island",
    "Khalifa City",
    "Mohammed Bin Zayed City",
    "Mussafah",
    "Baniyas",
    "Saadiyat Island",
    "Corniche Area",
  ],
  Sharjah: [
    "Al Nahda",
    "Al Majaz",
    "Al Qasimia",
    "Al Khan",
    "Muwaileh",
    "Al Taawun",
    "Aljada",
    "University City",
    "Muwailih Commercial",
    "Al Mamzar",
  ],
  Ajman: [
    "Al Nuaimiya",
    "Al Rashidiya",
    "Al Jurf",
    "Al Mowaihat",
    "Al Rawda",
    "Ajman Downtown",
    "Corniche Ajman",
    "Al Rumaila",
  ],
  "Umm Al Quwain": [
    "UAQ Marina",
    "Al Salamah",
    "Al Raas",
    "Falaj Al Mualla",
    "Al Dar Al Baida",
  ],
  "Ras Al Khaimah": [
    "Al Nakheel",
    "Al Hamra",
    "Al Marjan Island",
    "Khuzam",
    "Mina Al Arab",
    "Julphar",
    "Al Dhait",
    "Dafan Al Khor",
  ],
  Fujairah: [
    "Fujairah City",
    "Al Faseel",
    "Sakamkam",
    "Dibba",
    "Mirbah",
    "Qidfa",
    "Masafi",
  ],
};

export const getAreasForEmirate = (emirate) => EMIRATE_AREAS[emirate] || [];

export const WARRANTY_OPTIONS = [
  "No",
  "Yes",
  "Dealer Warranty",
  "Manufacturer Warranty",
  "Extended Warranty",
];

export const SERVICE_HISTORY_OPTIONS = [
  "No",
  "Yes",
  "Partial",
  "Agency Maintained",
  "Independent Garage",
];

export const DOOR_OPTIONS = ["2", "3", "4", "5"];

export const CYLINDER_OPTIONS = ["3", "4", "5", "6", "8", "10", "12", "16"];

export const MIN_CAR_YEAR = 1986;

export const getYearOptions = (minYear = MIN_CAR_YEAR) => {
  const maxYear = new Date().getFullYear() + 1;
  const years = [];
  for (let year = maxYear; year >= minYear; year -= 1) {
    years.push(String(year));
  }
  return years;
};

export const EXTERIOR_COLOR_OPTIONS = [
  "Arctic White",
  "Pearl White",
  "Alpine White",
  "Biscay Blue",
  "Estoril Blue",
  "Midnight Blue",
  "Navy Blue",
  "Sapphire Black",
  "Jet Black",
  "Carbon Black",
  "Graphite Grey",
  "Mineral Grey",
  "Daytona Grey",
  "Mythos Black",
  "Obsidian Black",
  "Nardo Grey",
  "Lunar Grey",
  "Rhodium Silver",
  " Glacier Silver",
  "Florett Silver",
  "Canyon Red",
  "Misano Red",
  "Marina Bay Blue",
  "Gentian Blue",
  "Melbourne Red",
  "Sunset Orange",
  "Vegas Gold",
  "Havana Grey",
  "Himalaya Grey",
  "Orion Grey",
  "Sebring Blue",
  "Davana Grey",
  "Haiti Grey",
  "C Cairn Grey",
  "Skyscraper Grey",
  "Chalk",
  "Cashmere Grey",
  "Ivy Green",
  "British Racing Green",
  "Verde Mantis",
  "Formula Red",
  "Racing Red",
  " RossoCorsa",
  "Giallo Orion",
  "Blu Corsa",
  "Rosso Mugello",
  "Rosso Scuderia",
  "Nero",
  "Bianco",
  "Grigio",
  "Argento",
  "Blu",
  "Verde",
  "Giallo",
];

export const INTERIOR_COLOR_OPTIONS = [
  "Black",
  "Ebony Black",
  "Tan",
  "Beige",
  "Camel",
  "Sandstorm",
  "Saddle Tan",
  "Ivory",
  "Cream",
  "Oyster",
  "Grey",
  "Space Grey",
  "Mist Grey",
  "Cerry Grey",
  "Espresso",
  "Cappuccino",
  "Navy",
  "Blue",
  "Cocoa",
  "Bourbon",
  "Sahara",
  "Chestnut",
  "Marron",
  "Tobacco",
  "Russet",
  "Caramel",
  "Nougat",
  "Silk",
  "Sepia",
  "Stone",
  "Slate",
  "Graphite",
  "Charcoal",
];

export const FUEL_EFFICIENCY_OPTIONS = [
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30+",
];

export const TAG_OPTIONS = [
  "Lady Driven",
  "Doctor Driven",
  "Expat Owned",
  "Executive Driven",
];
